workflows:
  android_build:
    name: Android Build
    environment:
      java: 17
      vars:
        GRADLE_WRAPPER: "./gradlew"
      groups:
        - local-properties
    scripts:
      - name: Enable Permission
        script: chmod +x $GRADLE_WRAPPER
      - name: Set up environment
        script: |
          echo "Setting up environment"
          echo "BASE_URL=$BASE_URL" > $CM_BUILD_DIR/local.properties
          echo "API_KEY=$API_KEY" >> $CM_BUILD_DIR/local.properties
      - name: Run Unit Tests
        script: |
          echo "Running unit tests"
          $GRADLE_WRAPPER test
      - name: Build APK
        script: $GRADLE_WRAPPER assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk