workflows:
  android_build:
    name: Android Build
    environment:
      java: 17
      vars:
        GRADLE_WRAPPER: "./gradlew"
    scripts:
      - name: Enable Permission
        script: chmod +x $GRADLE_WRAPPER
      - name: Set up environment
        script: echo "Setting up environment"
      - name: Build APK
        script: $GRADLE_WRAPPER assembleRelease
    artifacts:
      - build/outputs/apk/release/*.apk
